import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.117.1/+esm";
const SUPABASE_URL="https://dxmyyymeyypxcjtmelvj.supabase.co";const SUPABASE_KEY="sb_publishable_Tp-IbPEmWXuBvZ8md8CY7Q_TCua9njd";const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const esc=(s="")=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));const fmt=s=>new Date(s).toLocaleString([],{dateStyle:"medium",timeStyle:"short"});const statusLabel=s=>String(s||"").replace(/_/g," ").replace(/^customer reply$/i,"applicant reply");
const loginView=document.querySelector("#loginView"),dash=document.querySelector("#dashboardView"),loginForm=document.querySelector("#loginForm"),loginStatus=document.querySelector("#loginStatus"),list=document.querySelector("#applicationList"),detail=document.querySelector("#detail"),count=document.querySelector("#count");let apps=[],selectedId=null;
async function checkAdmin(){const {data:{user}}=await supabase.auth.getUser();if(!user)return showLogin();const {data,error}=await supabase.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle();if(error||!data){await supabase.auth.signOut({scope:"local"});loginStatus.className="status error";loginStatus.textContent="This account is not authorized as an admin.";return showLogin()}showDash();loadApps()}
function showLogin(){loginView.classList.remove("hidden");dash.classList.add("hidden")}function showDash(){loginView.classList.add("hidden");dash.classList.remove("hidden")}
async function loadApps(){const {data,error}=await supabase.from("applications").select("id,application_number,name,last_name,email,mobile_number,status,created_at,last_activity_at").order("last_activity_at",{ascending:false});if(error){detail.innerHTML='<div class="status error">Unable to load applications: '+esc(error.message)+"</div>";return}apps=data||[];count.textContent=apps.length;list.innerHTML=apps.length?apps.map(a=>'<div class="application '+(a.id===selectedId?"active":"")+'" data-id="'+esc(a.id)+'"><strong>'+esc(a.application_number)+"</strong><small>"+esc([a.name,a.last_name].filter(Boolean).join(" "))+" · "+esc(fmt(a.last_activity_at))+'</small><span class="badge">'+esc(statusLabel(a.status))+"</span></div>").join(""):'<div class="empty" style="min-height:220px">No applications yet.</div>';list.querySelectorAll(".application").forEach(el=>el.addEventListener("click",()=>openApplication(el.dataset.id)));if(selectedId)openApplication(selectedId)}
async function openApplication(id){selectedId=id;const a=apps.find(x=>x.id===id);if(!a)return;list.querySelectorAll(".application").forEach(el=>el.classList.toggle("active",el.dataset.id===id));const {data:messages,error}=await supabase.from("messages").select("id,sender_type,message,created_at").eq("application_id",id).order("created_at",{ascending:true});if(error){detail.innerHTML='<div class="status error">'+esc(error.message)+"</div>";return}detail.innerHTML='<div class="detail-head"><div><h2>'+esc(a.application_number)+"</h2><p>"+esc([a.name,a.last_name].filter(Boolean).join(" "))+" · "+esc(a.email)+" · "+esc(a.mobile_number)+"</p></div><span class=\"badge\">"+esc(statusLabel(a.status))+'</span></div><div class="messages">'+(messages||[]).map(m=>'<div class="bubble '+esc(m.sender_type)+'"><small>'+esc(m.sender_type==="admin"?"Admin":"Applicant")+" · "+esc(fmt(m.created_at))+"</small>"+esc(m.message).replace(/\\n/g,"<br>")+"</div>").join("")+'</div><form class="reply" id="adminReplyForm"><label>Reply<textarea name="message" required maxlength="5000" placeholder="Reply to the applicant..."></textarea></label><button class="button" type="submit">Send Reply</button><p class="status" id="replyStatus"></p></form>';document.querySelector("#adminReplyForm").addEventListener("submit",sendAdminReply)}
async function sendAdminReply(e){e.preventDefault();const f=e.currentTarget,b=f.querySelector("button"),st=document.querySelector("#replyStatus"),msg=String(new FormData(f).get("message")||"").trim();if(!msg)return;b.disabled=true;st.className="status";st.textContent="Sending...";const {error}=await supabase.from("messages").insert({application_id:selectedId,sender_type:"admin",message:msg});if(error){st.className="status error";st.textContent=error.message}else{f.reset();st.className="status success";st.textContent="Reply sent.";await loadApps()}b.disabled=false}
loginForm.addEventListener("submit",async e=>{e.preventDefault();const b=document.querySelector("#loginButton");b.disabled=true;loginStatus.className="status";loginStatus.textContent="Signing in...";const form=new FormData(loginForm);const {error}=await supabase.auth.signInWithPassword({email:form.get("email"),password:form.get("password")});if(error){loginStatus.className="status error";loginStatus.textContent=error.message}else{loginForm.reset();await checkAdmin()}b.disabled=false});
document.querySelector("#logoutButton").addEventListener("click",async()=>{await supabase.auth.signOut({scope:"local"});showLogin()});supabase.auth.onAuthStateChange(()=>checkAdmin());checkAdmin();
supabase.channel("admin-inbox").on("postgres_changes",{event:"*",schema:"public",table:"applications"},()=>loadApps()).on("postgres_changes",{event:"*",schema:"public",table:"messages"},()=>{loadApps()}).subscribe();